name: Test Refersion Integration

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run daily at 8 AM UTC to catch any breaking changes
    - cron: '0 8 * * *'
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Test type to run'
        required: false
        default: 'all'
        type: choice
        options:
          - all
          - quick
          - browser

jobs:
  quick-test:
    name: Quick Integration Test
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.test_type != 'browser' }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Run quick test
      run: |
        node test-loop-quick.js
        
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: quick-test-results
        path: test-*.log
        retention-days: 7

  browser-test:
    name: Full Browser Test
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.test_type != 'quick' }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Install Puppeteer system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libnss3 \
          libatk-bridge2.0-0 \
          libdrm2 \
          libxkbcommon0 \
          libxcomposite1 \
          libxdamage1 \
          libxfixes3 \
          libxrandr2 \
          libgbm1 \
          libasound2
          
    - name: Run browser test
      run: |
        npm run test:loop
      env:
        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: false
        
    - name: Upload screenshots
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: browser-test-screenshots
        path: test-*.png
        retention-days: 7
        
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: browser-test-results
        path: test-*.log
        retention-days: 7

  notify-failure:
    name: Notify on Failure
    runs-on: ubuntu-latest
    needs: [quick-test, browser-test]
    if: failure()
    
    steps:
    - name: Create issue on failure
      uses: actions/github-script@v7
      with:
        script: |
          const title = `Integration Test Failed - ${new Date().toISOString().split('T')[0]}`;
          const body = `
          ## Integration Test Failure
          
          The Refersion integration test failed on ${context.sha}.
          
          **Workflow Run**: [${context.runId}](${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId})
          **Commit**: ${context.sha}
          **Branch**: ${context.ref}
          
          Please check the test artifacts for screenshots and logs.
          `;
          
          // Check if issue already exists for today
          const issues = await github.rest.issues.listForRepo({
            owner: context.repo.owner,
            repo: context.repo.repo,
            labels: 'integration-test-failure',
            state: 'open'
          });
          
          const today = new Date().toISOString().split('T')[0];
          const existingIssue = issues.data.find(issue => issue.title.includes(today));
          
          if (!existingIssue) {
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: title,
              body: body,
              labels: ['integration-test-failure', 'automated']
            });
          }